### ISSUE TITLE
@<file> support ignores files to compile

### ISSUE THREAD

**Issue by gdrouet** [theblacksmith/typescript-compiler#10]
The @<file> could also contains files. For instance I can have something like this: foo.ts bar.ts --sourcemap -t ES3 --out  aggregate.js
If I do this: compile([], '@args.txt') ==> foo.ts and bar.ts are ignored and I must indicate them in the first argument. Can you add file support in @<file> please?

**Comment by svallory** [comment]
:ship:'ed

**Comment by gdrouet** [comment]
It works fine :-)
